name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
permissions: {}
jobs:
  update-semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - uses: haya14busa/action-update-semver@7d2c558640ea49e798d46539536190aff8c18715 # v1
